#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('FIZZBUZZ_COMPOSER_INSTALL', $file);
        break;
    }
}

if (!defined('FIZZBUZZ_COMPOSER_INSTALL')) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

require FIZZBUZZ_COMPOSER_INSTALL;

use Hnw\SingleSubcommandConsole\Application; 
use Hnw\FizzBuzz\FizzBuzzCommand;

$app = new Application('fizzbuzz', '0.0.2');
$app->add(new FizzBuzzCommand());
$app->run();
